# Generated by Django 3.2.10 on 2021-12-24 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComments',
        ),
    ]
